### ISSUE TITLE
[Apple] "apptest" and "nonce" params - where and how to obtain them?

### ISSUE THREAD

**Issue by GildedHonour** [dreipol/pyattest#8]
```
config = AppleConfig(key_id=key_id, app_id='1234ABCDEF.ch.dreipol.demo', production=True)
attestation = Attestation(attest, nonce, config)

try:
    attestation.verify()
except PyAttestException as exception:
    # Do your thing
    pass

```
The `app_id` and `key_id` are generated in the developer's dashboard, right?

What about `attest` and `nonce` - how and where are they obtained? I've done a research and come to the conclusion that in order to obtain them it's required to run some Swift code on an iOS device for the **first time and once**. In other words, they are generated by an **iOS device only.** 

```
import DCAppAttest

func generateKeyAndAttestation() {
    guard let attestationKey = DCAppAttestService.shared.generateKey() else {
        print("Error generating attestation key.")
        return
    }

    // Generate a nonce (you may need to use a more secure source for your actual use case)
    let nonce = Data.random(count: 32)

    // Prepare the data to be attested
    let dataToAttest = "Data to be attested".data(using: .utf8)!

    // Concatenate nonce and data
    var attestationData = nonce
    attestationData.append(dataToAttest)

    // Use DCAppAttestService to attest the data
    guard let attestation = DCAppAttestService.shared.attestData(attestationData, withKey: attestationKey) else {
        print("Error generating attestation.")
        return
    }

    // Print or use the attestation key and the resulting attestation
    print("Attestation Key: \(attestationKey)")
    print("Attestation: \(attestation)")
}
```

Once run and obtained, they may be used and reused from then on in Python or any other language. 

When one needs a new pair, one will run the code again. 

Correct?

**Comment by lailabecker** [comment]
Hi @GildedHonour
You're on the right track. There are 2 steps to using App Attest:

1. You generate a cryptographic key and register it with your server. To ensure that this key comes from a legitimate iOS device you ask Apple's server to verify that for you and obtain an **attestation**. You can do this with `DCAppAttestService.shared.attestKey(attestationKey, clientDataHash: nonce) { ... }`. Please note that you should obtain the nonce from your server to prevent replay attacks.
2. After you successfully registered your key with the server you can then use that key to sign your requests. In Apple's terminology this is called an **assertion** and it does not require a request to Apple's server. To obtain an assertion you first generate a hash of your request. How you do that is up to you but you should obviously make sure that any data you want to protect from tempering is part of the hash. You can then call `DCAppAttestService.shared.generateAssertion(attestationKey, clientDataHash: hash) { ... }` to generate your assertion. On the server side you can use pyAttest to verify the signature using:
``` python
config = AppleConfig(key_id=key_id, app_id='1234ABCDEF.ch.dreipol.demo', production=True)
assertion = // get from your request
expected_hash = // generate hash in the same way you did on your iOS device
pem_key = // retrieve the key you registered in step 1
assertion = Assertion(assertion, expected_hash, pem_key, config)
assertion.verify()
```

You can also checkout [Apple's documentation](https://developer.apple.com/documentation/devicecheck/establishing_your_app_s_integrity) for more info on App Attest. You can also check out [our implementation](https://github.com/dreipol/django-dreiattest) of the whole end-to-end procedure in django as well as our client side implementations for [Alamofire](https://github.com/dreipol/dreiAttest-ios) and [ktor](https://github.com/dreipol/dreiAttest-android).

**Comment by lailabecker** [comment]
By the way you should also set `production=False` unless you are using an AppStore / TestFlight build of your app. Otherwise the verification will fail.

**Comment by GildedHonour** [comment]
@lailabecker alright. 

I saw the Apple documentation.

Do you know if  an attestation can be generated by any other language, except Object-C, or rather on any plathorm **initially** other than iOS? Non Apple. 

It's because it won't be a single **attestation** that I'll obtain once in half year, but I'll need to do so regularly, for each my customers.  Meaning, on daily basis. If I understand correctly that I'll a new attest for **each new client**.

Also, there's TTL for attestation; it'll require self-refreshment **run on iOS** again every 60 min?

All in all, I'm looking into a way to do as much of this in Python as possible, outside of iOS. In order to automate all of it.

Any idea?

**Comment by lailabecker** [comment]
Hi @GildedHonour
I'm not sure I understand what you're trying to achieve. It sounds like you want to manually generate key pairs and distribute them to your users so they can authenticate with your server. If that's what you're trying to do App Attest is not the right tool for that. The goal of App Attest is to verify your app is genuine not to authenticate users.

To answer your questions:
Yes, each app client needs to register it's key the first time it talks to your server but after that you can use the key you registered to sign requests for as log as you like. So you don't need to generate another attestation after 60 min. It is not possible to generate an attestation on a non-Apple platform because the point of App Attest is to ensure your server is talking to a genuine instance of your app running on a genuine Apple device. For Android there's a similar service available, however, called [Play Integrety](https://developer.android.com/google/play/integrity/overview). As for using other languages: the API is only available vor objc and Swift but there are other languages that are interoperable with objc. E.g. we wrote some wrappers for usage in kotlin multiplatform projects. You can find them [here](https://github.com/dreipol/dreiAttest-android/tree/develop/multiplatform/src/iosMain/kotlin/ch/dreipol/dreiattest/multiplatform).

**Comment by GildedHonour** [comment]
@lailabecker 
Ok

> running on a genuine Apple device. 

does it have to be a real, **physical** Apple device or will a VPS with MacOS do to?

**Comment by GildedHonour** [comment]
@lailabecker any idea?

**Comment by lailabecker** [comment]
No, it's not supported. The [documentation states](https://developer.apple.com/documentation/devicecheck/dcappattestservice/3573915-issupported):
> If you read isSupported from an app running on a Mac device, the value is false.

And it wouldn't make sense to run App Attest server side anyway because you control it and can verify its integrity that way. The point of App Attest is to verify the integrity of your clients.

**Comment by GildedHonour** [comment]
MacOS appears there

![imagen](https://github.com/dreipol/pyattest/assets/2032888/04a083eb-c7c5-491a-9a0f-ca971e9f4774)


Cheers

**Comment by lailabecker** [comment]
The class / property is there, yes. But if you scroll down a little bit you'll find the sentence I quoted stating that `DCAppAttestService.shared.isSupported` always returns `false` on macOS.
